added mail notification

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -13,20 +13,15 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-
       - uses: actions/setup-node@v3
         with:
           node-version: 18
-
       - name: Install dependencies
         run: npm ci
-
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
-
       - name: Set up xvfb
         run: sudo apt-get install xvfb
-
       - name: Run Playwright tests
         env:  # Set environment variables from secrets
           BASE_URL: ${{ secrets.DEV_URL }}
@@ -37,31 +32,29 @@ jobs:
           ADMIN_PASSWORD: ${{ secrets.ADMIN_DEV_PASSWORD }}
           USER_NAME: ${{ secrets.USER_DEV_NAME }}
           USER_PASSWORD: ${{ secrets.USER_DEV_PASSWORD }}
-        run: xvfb-run -a npx playwright test
-
+        run: (xvfb-run -a npx playwright test > test-output.log 2>&1) || echo "Playwright tests failed!"
+      - name: Generate Test Summary
+        run: |
+          grep -E '✓|✕' test-output.log > test-summary.txt
       - name: Install Allure
         run: npm install -g allure-commandline
-
       - name: Generate Allure Report
         run: allure generate allure-results --clean -o allure-report
-
       - uses: actions/upload-artifact@v3
         if: always()
         with:
           name: playwright-report
           path: allure-report/
           retention-days: 30
-
-      - name: Send email with Allure Report
+      - name: Send email with test summary
         uses: dawidd6/action-send-mail@v3
         with:
           server_address: smtp.gmail.com
           server_port: 465
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
-          subject: Playwright Test Report
-          body: Here is the latest Playwright test report.
+          subject: Playwright Test Summary
+          body: Here is the summary of Playwright tests.
           to: ${{ secrets.RECIPIENT }}
           from: ${{ secrets.MAIL_USERNAME }}
-          content_type: text/html
-          attachments: allure-report/index.html  # adjust if the main report file has a different name or path
+          attachments: test-summary.txt
